"""description_of_change

Revision ID: ebdee18538d1
Revises: 0002_customer_wallet
Create Date: 2026-09-13 13:12:32.641866
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebdee18538d1'
down_revision: Union[str, None] = '0002_customer_wallet'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tool_execution_logs_analysis_id', table_name='tool_execution_logs')
    op.drop_index('ix_tool_execution_logs_request_id', table_name='tool_execution_logs')
    op.drop_index('ix_tool_execution_logs_tool_name', table_name='tool_execution_logs')
    op.drop_table('tool_execution_logs')
    op.drop_index('ix_images_request_id', table_name='images')
    op.drop_index('ix_images_session_id', table_name='images')
    op.drop_index('ix_images_user_id', table_name='images')
    op.drop_table('images')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_whatsapp_ingestions_external_message_id', table_name='whatsapp_ingestions')
    op.drop_index('ix_whatsapp_ingestions_external_user_id', table_name='whatsapp_ingestions')
    op.drop_index('ix_whatsapp_ingestions_request_id', table_name='whatsapp_ingestions')
    op.drop_table('whatsapp_ingestions')
    op.drop_index('ix_onboarding_sessions_whatsapp_id', table_name='onboarding_sessions')
    op.drop_table('onboarding_sessions')
    op.drop_index('ix_retry_history_analysis_id', table_name='retry_history')
    op.drop_index('ix_retry_history_request_id', table_name='retry_history')
    op.drop_table('retry_history')
    op.drop_index('ix_analyses_image_id', table_name='analyses')
    op.drop_index('ix_analyses_request_id', table_name='analyses')
    op.drop_index('ix_analyses_user_id', table_name='analyses')
    op.drop_table('analyses')
    op.drop_index('ix_reports_analysis_id', table_name='reports')
    op.drop_index('ix_reports_user_id', table_name='reports')
    op.drop_table('reports')
    op.drop_index('ix_history_analysis_id', table_name='history')
    op.drop_index('ix_history_user_id', table_name='history')
    op.drop_table('history')
    op.drop_index('ix_version_history_analysis_id', table_name='version_history')
    op.drop_index('ix_version_history_request_id', table_name='version_history')
    op.drop_table('version_history')
    op.drop_index('ix_processing_logs_processing_step', table_name='processing_logs')
    op.drop_index('ix_processing_logs_request_id', table_name='processing_logs')
    op.drop_table('processing_logs')
    op.drop_index('ix_audit_logs_action', table_name='audit_logs')
    op.drop_index('ix_audit_logs_request_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_session_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_user_id', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_customers_whatsapp_id', table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('whatsapp_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('business_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('gst_number', sa.VARCHAR(length=20), nullable=False),
    sa.Column('address', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('wallet_balance', sa.INTEGER(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_registered', sa.BOOLEAN(), server_default=sa.text('1'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_customers_whatsapp_id', 'customers', ['whatsapp_id'], unique=1)
    op.create_table('audit_logs',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('session_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('request_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('action', sa.VARCHAR(length=100), nullable=False),
    sa.Column('resource_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('resource_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('ip_address', sa.VARCHAR(length=45), nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=500), nullable=True),
    sa.Column('details', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_index('ix_audit_logs_session_id', 'audit_logs', ['session_id'], unique=False)
    op.create_index('ix_audit_logs_request_id', 'audit_logs', ['request_id'], unique=False)
    op.create_index('ix_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.create_table('processing_logs',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('request_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('processing_step', sa.VARCHAR(length=100), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('started_at', sa.DATETIME(), nullable=False),
    sa.Column('finished_at', sa.DATETIME(), nullable=True),
    sa.Column('processing_time', sa.FLOAT(), nullable=True),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('metadata_json', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['images.request_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_processing_logs_request_id', 'processing_logs', ['request_id'], unique=False)
    op.create_index('ix_processing_logs_processing_step', 'processing_logs', ['processing_step'], unique=False)
    op.create_table('version_history',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('request_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('analysis_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('version_number', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('result_json', sa.TEXT(), nullable=True),
    sa.Column('summary', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['images.request_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_version_history_request_id', 'version_history', ['request_id'], unique=False)
    op.create_index('ix_version_history_analysis_id', 'version_history', ['analysis_id'], unique=False)
    op.create_table('history',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('analysis_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('image_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('product_name', sa.VARCHAR(length=500), nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('estimated_price', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_history_user_id', 'history', ['user_id'], unique=False)
    op.create_index('ix_history_analysis_id', 'history', ['analysis_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('analysis_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('report_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('format', sa.VARCHAR(length=10), nullable=False),
    sa.Column('filename', sa.VARCHAR(length=500), nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=1000), nullable=False),
    sa.Column('file_size', sa.INTEGER(), nullable=True),
    sa.Column('page_count', sa.INTEGER(), nullable=True),
    sa.Column('include_charts', sa.BOOLEAN(), nullable=False),
    sa.Column('generated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reports_user_id', 'reports', ['user_id'], unique=False)
    op.create_index('ix_reports_analysis_id', 'reports', ['analysis_id'], unique=False)
    op.create_table('analyses',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('request_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('image_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('processing_time', sa.FLOAT(), nullable=True),
    sa.Column('retry_count', sa.INTEGER(), nullable=False),
    sa.Column('version_number', sa.INTEGER(), nullable=False),
    sa.Column('material', sa.VARCHAR(length=255), nullable=True),
    sa.Column('gold_purity', sa.VARCHAR(length=100), nullable=True),
    sa.Column('weight', sa.FLOAT(), nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), nullable=True),
    sa.Column('estimated_price', sa.FLOAT(), nullable=True),
    sa.Column('confidence', sa.FLOAT(), nullable=True),
    sa.Column('gemstones', sa.TEXT(), nullable=True),
    sa.Column('style', sa.VARCHAR(length=100), nullable=True),
    sa.Column('era', sa.VARCHAR(length=100), nullable=True),
    sa.Column('condition', sa.VARCHAR(length=255), nullable=True),
    sa.Column('summary', sa.TEXT(), nullable=True),
    sa.Column('raw_response', sa.TEXT(), nullable=True),
    sa.Column('analyzed_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['images.request_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_analyses_user_id', 'analyses', ['user_id'], unique=False)
    op.create_index('ix_analyses_request_id', 'analyses', ['request_id'], unique=False)
    op.create_index('ix_analyses_image_id', 'analyses', ['image_id'], unique=False)
    op.create_table('retry_history',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('request_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('analysis_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('attempt_number', sa.INTEGER(), nullable=False),
    sa.Column('retry_time', sa.DATETIME(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('result_summary', sa.TEXT(), nullable=True),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('processing_time', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['images.request_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_retry_history_request_id', 'retry_history', ['request_id'], unique=False)
    op.create_index('ix_retry_history_analysis_id', 'retry_history', ['analysis_id'], unique=False)
    op.create_table('onboarding_sessions',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('whatsapp_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('state', sa.VARCHAR(length=30), nullable=False),
    sa.Column('pending_data', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_onboarding_sessions_whatsapp_id', 'onboarding_sessions', ['whatsapp_id'], unique=1)
    op.create_table('whatsapp_ingestions',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('request_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('external_user_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('external_message_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('external_media_id', sa.VARCHAR(length=200), nullable=True),
    sa.Column('channel', sa.VARCHAR(length=20), nullable=False),
    sa.Column('caption', sa.TEXT(), nullable=True),
    sa.Column('mime_type', sa.VARCHAR(length=100), nullable=True),
    sa.Column('timestamp', sa.VARCHAR(length=50), nullable=True),
    sa.Column('image_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('file_size', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_whatsapp_ingestions_request_id', 'whatsapp_ingestions', ['request_id'], unique=1)
    op.create_index('ix_whatsapp_ingestions_external_user_id', 'whatsapp_ingestions', ['external_user_id'], unique=False)
    op.create_index('ix_whatsapp_ingestions_external_message_id', 'whatsapp_ingestions', ['external_message_id'], unique=1)
    op.create_table('users',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=255), nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('is_verified', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_username', 'users', ['username'], unique=1)
    op.create_index('ix_users_email', 'users', ['email'], unique=1)
    op.create_table('images',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('request_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('original_filename', sa.VARCHAR(length=500), nullable=False),
    sa.Column('stored_filename', sa.VARCHAR(length=500), nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=1000), nullable=False),
    sa.Column('file_size', sa.INTEGER(), nullable=False),
    sa.Column('mime_type', sa.VARCHAR(length=100), nullable=False),
    sa.Column('image_hash', sa.VARCHAR(length=64), nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=1000), nullable=False),
    sa.Column('width', sa.INTEGER(), nullable=True),
    sa.Column('height', sa.INTEGER(), nullable=True),
    sa.Column('processing_status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_images_user_id', 'images', ['user_id'], unique=False)
    op.create_index('ix_images_session_id', 'images', ['session_id'], unique=False)
    op.create_index('ix_images_request_id', 'images', ['request_id'], unique=1)
    op.create_table('tool_execution_logs',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('request_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('analysis_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('tool_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('execution_order', sa.INTEGER(), nullable=False),
    sa.Column('started_at', sa.DATETIME(), nullable=False),
    sa.Column('finished_at', sa.DATETIME(), nullable=True),
    sa.Column('execution_time', sa.FLOAT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('output_summary', sa.TEXT(), nullable=True),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['images.request_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tool_execution_logs_tool_name', 'tool_execution_logs', ['tool_name'], unique=False)
    op.create_index('ix_tool_execution_logs_request_id', 'tool_execution_logs', ['request_id'], unique=False)
    op.create_index('ix_tool_execution_logs_analysis_id', 'tool_execution_logs', ['analysis_id'], unique=False)
    # ### end Alembic commands ###
